mapper:
  map:
    general:
      world_frame: "odom"
      thresholding_period: { seconds: 2.0 }
      pruning_period: { seconds: 10.0 }
      publication_period: { seconds: 2.0 }
    data_structure:
      type: "hashed_wavelet_octree"
      min_cell_width: { meters: 0.1 }
      tree_height: 6

  inputs:
    - type: "pointcloud"
      general:
        topic_name: "/livox/lidar"
        topic_type: "livox"
        topic_queue_length: 1
        max_wait_for_pose: { seconds: 1.0 }
        reprojected_pointcloud_topic_name: "lidar_input"
        # projected_range_image_topic_name: "/wavemap/lidar_range_image"
      integrators:
        - integration_method:
            type: "hashed_wavelet_integrator"
            min_range: { meters: 0.5 }
            max_range: { meters: 15.0 }
            termination_update_error: 0.1
            termination_height: 0
          projection_model:
            type: "spherical_projector"
            elevation:
              num_cells: 32
              min_angle: { degrees: -7.0 }
              max_angle: { degrees: 52.0 }
            azimuth:
              num_cells: 512
              min_angle: { degrees: -180.0 }
              max_angle: { degrees: 180.0 }
          measurement_model:
            type: "continuous_beam"
            angle_sigma: { degrees: 0.035 }
            # NOTE: For best results, we recommend setting range_sigma to
            #       max(min_cell_width / 2, ouster_noise) where ouster_noise = 0.05
            range_sigma: { meters: 0.05 }
            scaling_free: 0.2
            scaling_occupied: 0.4
